const images = {
    Logo : require("../assets/images/Logo.png"),
    BackGroundImage : require("../assets/images/BackGroudImage.png"),
    LoginBack : require("../assets/images/LoginBack.png"),
    SignupBack : require("../assets/images/SignupBack.png"),
    LeftArrow : require("../assets/images/LeftArrow.png"),
    PasswordEye : require("../assets/images/PasswordEye.png"),
    Camera : require("../assets/images/Camera.png"),
    Collection : require("../assets/images/Collection.png"),
    Notification : require("../assets/images/Notification.png"),
    Chat : require("../assets/images/Chat.png"),
    Home : require("../assets/images/Home.png"),
    Plus : require("../assets/images/Plus.png"),
    Menu : require("../assets/images/Menu.png"),
    User : require("../assets/images/User.png"),
    ActiveHome : require("../assets/images/ActiveHome.png"),
    Search : require("../assets/images/Search.png"),
    Filter : require("../assets/images/Filter.png"),
    More : require("../assets/images/More.png"),
    Location : require("../assets/images/Location.png"),
    Dollor : require("../assets/images/Dollor.png"),
    Cross : require("../assets/images/Cross.png"),
    ShareIcon : require("../assets/images/ShareIcon.png"),
    Report : require("../assets/images/Report.png"),
    EditProfile: require("../assets/images/EditProfile.png"),
    ViewProfile: require("../assets/images/ViewProfile.png"),
    UploadDemo: require("../assets/images/UploadDemo.png"),
    ViewPost: require("../assets/images/ViewPost.png"),
    Setting: require("../assets/images/Setting.png"),
    Advertisment: require("../assets/images/Advertisment.png"),
    BookingDetails: require("../assets/images/BookingDetails.png"),
    BackDollor: require("../assets/images/BackDollor.png"),
    Friends: require("../assets/images/Friends.png"),
    Logout: require("../assets/images/Logout.png"),
    HelpCenter: require("../assets/images/HelpCenter.png"),
    PaymentMethod: require("../assets/images/PaymentMethod.png"),
    MyBooking: require("../assets/images/MyBooking.png"),
    AboutUs: require("../assets/images/AboutUs.png"),
    RightArrow: require("../assets/images/RightArrow.png"),
    WhiteCamera: require("../assets/images/WhiteCamera.png"),
    HorizantalDots: require("../assets/images/HorizantalDots.png"),
    WhiteChat: require("../assets/images/WhiteChat.png"),
    WhiteMore: require("../assets/images/WhiteMore.png"),
    ChatUser: require("../assets/images/ChatUser.png"),
    Send: require("../assets/images/Send.png"),
    WhiteNotification: require("../assets/images/WhiteNotification.png"),
    Star: require("../assets/images/Star.png"),
    GreenCheck: require("../assets/images/GreenCheck.png"),
    Stripe: require("../assets/images/Stripe.png"),
    PayPal: require("../assets/images/PayPal.png"),
    MasterCard: require("../assets/images/MasterCard.png"),
    DownArrow: require("../assets/images/DownArrow.png"),
    Party: require("../assets/images/Party.png"),
   

}

export default images